// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinhaCarteiraRazor.Data;

namespace MinhaCarteiraRazor.Data.Migrations
{
    [DbContext(typeof(MinhaCarteiraDbContext))]
    [Migration("20190914140043_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("MinhaCarteiraRazor.Core.Entities.Carteira", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Atual");

                    b.Property<decimal>("Investido");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120);

                    b.Property<int?>("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Carteiras");
                });

            modelBuilder.Entity("MinhaCarteiraRazor.Core.Entities.Operacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CarteiraId");

                    b.Property<DateTime>("Data");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<decimal>("PrecoEntrada");

                    b.Property<decimal>("PrecoGain");

                    b.Property<decimal>("PrecoStop");

                    b.Property<decimal>("Resultado");

                    b.Property<int>("Tipo");

                    b.HasKey("Id");

                    b.HasIndex("CarteiraId");

                    b.ToTable("Operacoes");
                });

            modelBuilder.Entity("MinhaCarteiraRazor.Core.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160);

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(160);

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("MinhaCarteiraRazor.Core.Entities.Carteira", b =>
                {
                    b.HasOne("MinhaCarteiraRazor.Core.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("MinhaCarteiraRazor.Core.Entities.Operacao", b =>
                {
                    b.HasOne("MinhaCarteiraRazor.Core.Entities.Carteira", "Carteira")
                        .WithMany()
                        .HasForeignKey("CarteiraId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
